[package]
name = "screeps-rs"
version = "0.0.1"
authors = ["Sam Martin"]
edition = "2018"

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = "0.7"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
